spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: zy
    password: Z123456y
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    # 邮件服务地址
    host: smtp.163.com
    # 端口,可不写默认
    port: 465
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: numberplate@163.com
    from: numberplate@163.com
    # 授权码
    password: PQTMEXNUEVECVOMT
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000
server:
  port: 8181


mybatis:
  type-aliases-package: com.numberplate.numberplateserver.entity
  config-location: classpath:mybatis.xml